// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Example",
    defaultLocalization: "en",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Example",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.oslogviewer.example",
            teamIdentifier: "3S7EA557V7",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    dependencies: [
        // The sample is the runtime/execution environment for the local OSLogViewer,
        // so it must reference the package on disk (not a published release).
        .package(path: "..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "OSLogViewer", package: "OSLogViewer")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)